import type { GraphNode, GraphEdge } from '../../../shared/types/graph';
import type { GraphDepth } from '../../../shared/types/graph';

/**
 * Mock graph data — auto-generated from barber.io parser output
 * Generated by: cargo run --bin parse_project -- ~/_dev/barber.io
 * Stats: 14 modules, 72 files, 42 module imports, 149 file imports, 11 side-effect imports
 */

// ─── Packages (from requirements.txt) ───
const packages: GraphNode[] = [
  { id: 'package:fastapi', type: 'package', label: 'fastapi' },
  { id: 'package:sqlalchemy', type: 'package', label: 'sqlalchemy' },
  { id: 'package:python-jose', type: 'package', label: 'python-jose' },
  { id: 'package:google-auth', type: 'package', label: 'google-auth' },
  { id: 'package:pymysql', type: 'package', label: 'pymysql' },
  { id: 'package:alembic', type: 'package', label: 'alembic' },
  { id: 'package:uvicorn', type: 'package', label: 'uvicorn' },
];

// ─── Modules & Groups ───
const modules: GraphNode[] = [
  { id: 'module:.', type: 'module', label: 'barber.io', path: '.' },
  { id: 'module:core', type: 'module', label: 'core', path: 'core' },
  { id: 'module:modules', type: 'group', label: 'modules', path: 'modules' },
  { id: 'module:modules/admin', type: 'module', label: 'admin', path: 'modules/admin' },
  { id: 'module:modules/admin_auth', type: 'module', label: 'admin_auth', path: 'modules/admin_auth' },
  { id: 'module:modules/event', type: 'module', label: 'event', path: 'modules/event' },
  { id: 'module:modules/gacha', type: 'module', label: 'gacha', path: 'modules/gacha' },
  { id: 'module:modules/misc', type: 'module', label: 'misc', path: 'modules/misc' },
  { id: 'module:modules/notice', type: 'module', label: 'notice', path: 'modules/notice' },
  { id: 'module:modules/ranking', type: 'module', label: 'ranking', path: 'modules/ranking' },
  { id: 'module:modules/shop', type: 'module', label: 'shop', path: 'modules/shop' },
  { id: 'module:modules/user', type: 'module', label: 'user', path: 'modules/user' },
  { id: 'module:modules/user_event_log', type: 'module', label: 'user_event_log', path: 'modules/user_event_log' },
  { id: 'module:tests', type: 'module', label: 'tests', path: 'tests' },
];

// ─── Files ───
const files: GraphNode[] = [
  // core
  { id: 'file:core/CONSTANTS.py', type: 'file', label: 'CONSTANTS.py', path: 'core/CONSTANTS.py', language: 'python' },
  { id: 'file:core/database.py', type: 'file', label: 'database.py', path: 'core/database.py', language: 'python' },
  { id: 'file:core/exceptions.py', type: 'file', label: 'exceptions.py', path: 'core/exceptions.py', language: 'python' },
  { id: 'file:core/init_db.py', type: 'file', label: 'init_db.py', path: 'core/init_db.py', language: 'python' },
  { id: 'file:core/logging_config.py', type: 'file', label: 'logging_config.py', path: 'core/logging_config.py', language: 'python' },
  { id: 'file:core/misc.py', type: 'file', label: 'misc.py', path: 'core/misc.py', language: 'python' },
  { id: 'file:core/security.py', type: 'file', label: 'security.py', path: 'core/security.py', language: 'python' },

  // .
  { id: 'file:main.py', type: 'file', label: 'main.py', path: 'main.py', language: 'python' },

  // modules
  { id: 'file:modules/__init__.py', type: 'file', label: '__init__.py', path: 'modules/__init__.py', language: 'python' },

  // modules/admin
  { id: 'file:modules/admin/__init__.py', type: 'file', label: '__init__.py', path: 'modules/admin/__init__.py', language: 'python' },
  { id: 'file:modules/admin/router.py', type: 'file', label: 'router.py', path: 'modules/admin/router.py', language: 'python' },
  { id: 'file:modules/admin/service.py', type: 'file', label: 'service.py', path: 'modules/admin/service.py', language: 'python' },
  { id: 'file:modules/admin/ui_router.py', type: 'file', label: 'ui_router.py', path: 'modules/admin/ui_router.py', language: 'python' },

  // modules/admin_auth
  { id: 'file:modules/admin_auth/__init__.py', type: 'file', label: '__init__.py', path: 'modules/admin_auth/__init__.py', language: 'python' },
  { id: 'file:modules/admin_auth/models.py', type: 'file', label: 'models.py', path: 'modules/admin_auth/models.py', language: 'python' },
  { id: 'file:modules/admin_auth/repository.py', type: 'file', label: 'repository.py', path: 'modules/admin_auth/repository.py', language: 'python' },
  { id: 'file:modules/admin_auth/router.py', type: 'file', label: 'router.py', path: 'modules/admin_auth/router.py', language: 'python' },
  { id: 'file:modules/admin_auth/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/admin_auth/schemas.py', language: 'python' },
  { id: 'file:modules/admin_auth/service.py', type: 'file', label: 'service.py', path: 'modules/admin_auth/service.py', language: 'python' },
  { id: 'file:modules/admin_auth/session_service.py', type: 'file', label: 'session_service.py', path: 'modules/admin_auth/session_service.py', language: 'python' },

  // modules/event
  { id: 'file:modules/event/__init__.py', type: 'file', label: '__init__.py', path: 'modules/event/__init__.py', language: 'python' },
  { id: 'file:modules/event/attendance_models.py', type: 'file', label: 'attendance_models.py', path: 'modules/event/attendance_models.py', language: 'python' },
  { id: 'file:modules/event/attendance_repository.py', type: 'file', label: 'attendance_repository.py', path: 'modules/event/attendance_repository.py', language: 'python' },
  { id: 'file:modules/event/event_attendance_models.py', type: 'file', label: 'event_attendance_models.py', path: 'modules/event/event_attendance_models.py', language: 'python' },
  { id: 'file:modules/event/models.py', type: 'file', label: 'models.py', path: 'modules/event/models.py', language: 'python' },
  { id: 'file:modules/event/repository.py', type: 'file', label: 'repository.py', path: 'modules/event/repository.py', language: 'python' },
  { id: 'file:modules/event/service.py', type: 'file', label: 'service.py', path: 'modules/event/service.py', language: 'python' },

  // modules/gacha
  { id: 'file:modules/gacha/__init__.py', type: 'file', label: '__init__.py', path: 'modules/gacha/__init__.py', language: 'python' },
  { id: 'file:modules/gacha/balpan_models.py', type: 'file', label: 'balpan_models.py', path: 'modules/gacha/balpan_models.py', language: 'python' },
  { id: 'file:modules/gacha/balpan_repository.py', type: 'file', label: 'balpan_repository.py', path: 'modules/gacha/balpan_repository.py', language: 'python' },
  { id: 'file:modules/gacha/balpan_schemas.py', type: 'file', label: 'balpan_schemas.py', path: 'modules/gacha/balpan_schemas.py', language: 'python' },
  { id: 'file:modules/gacha/models.py', type: 'file', label: 'models.py', path: 'modules/gacha/models.py', language: 'python' },
  { id: 'file:modules/gacha/repository.py', type: 'file', label: 'repository.py', path: 'modules/gacha/repository.py', language: 'python' },
  { id: 'file:modules/gacha/router.py', type: 'file', label: 'router.py', path: 'modules/gacha/router.py', language: 'python' },
  { id: 'file:modules/gacha/router_logs.py', type: 'file', label: 'router_logs.py', path: 'modules/gacha/router_logs.py', language: 'python' },
  { id: 'file:modules/gacha/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/gacha/schemas.py', language: 'python' },
  { id: 'file:modules/gacha/service.py', type: 'file', label: 'service.py', path: 'modules/gacha/service.py', language: 'python' },

  // modules/misc
  { id: 'file:modules/misc/__init__.py', type: 'file', label: '__init__.py', path: 'modules/misc/__init__.py', language: 'python' },
  { id: 'file:modules/misc/router.py', type: 'file', label: 'router.py', path: 'modules/misc/router.py', language: 'python' },
  { id: 'file:modules/misc/router_logs.py', type: 'file', label: 'router_logs.py', path: 'modules/misc/router_logs.py', language: 'python' },
  { id: 'file:modules/misc/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/misc/schemas.py', language: 'python' },

  // modules/notice
  { id: 'file:modules/notice/__init__.py', type: 'file', label: '__init__.py', path: 'modules/notice/__init__.py', language: 'python' },
  { id: 'file:modules/notice/models.py', type: 'file', label: 'models.py', path: 'modules/notice/models.py', language: 'python' },
  { id: 'file:modules/notice/repository.py', type: 'file', label: 'repository.py', path: 'modules/notice/repository.py', language: 'python' },
  { id: 'file:modules/notice/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/notice/schemas.py', language: 'python' },
  { id: 'file:modules/notice/service.py', type: 'file', label: 'service.py', path: 'modules/notice/service.py', language: 'python' },

  // modules/ranking
  { id: 'file:modules/ranking/__init__.py', type: 'file', label: '__init__.py', path: 'modules/ranking/__init__.py', language: 'python' },
  { id: 'file:modules/ranking/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/ranking/schemas.py', language: 'python' },
  { id: 'file:modules/ranking/service.py', type: 'file', label: 'service.py', path: 'modules/ranking/service.py', language: 'python' },

  // modules/shop
  { id: 'file:modules/shop/__init__.py', type: 'file', label: '__init__.py', path: 'modules/shop/__init__.py', language: 'python' },
  { id: 'file:modules/shop/models.py', type: 'file', label: 'models.py', path: 'modules/shop/models.py', language: 'python' },
  { id: 'file:modules/shop/purchase_models.py', type: 'file', label: 'purchase_models.py', path: 'modules/shop/purchase_models.py', language: 'python' },
  { id: 'file:modules/shop/purchase_repository.py', type: 'file', label: 'purchase_repository.py', path: 'modules/shop/purchase_repository.py', language: 'python' },
  { id: 'file:modules/shop/repository.py', type: 'file', label: 'repository.py', path: 'modules/shop/repository.py', language: 'python' },
  { id: 'file:modules/shop/router.py', type: 'file', label: 'router.py', path: 'modules/shop/router.py', language: 'python' },
  { id: 'file:modules/shop/router_logs.py', type: 'file', label: 'router_logs.py', path: 'modules/shop/router_logs.py', language: 'python' },
  { id: 'file:modules/shop/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/shop/schemas.py', language: 'python' },
  { id: 'file:modules/shop/service.py', type: 'file', label: 'service.py', path: 'modules/shop/service.py', language: 'python' },

  // modules/user
  { id: 'file:modules/user/__init__.py', type: 'file', label: '__init__.py', path: 'modules/user/__init__.py', language: 'python' },
  { id: 'file:modules/user/models.py', type: 'file', label: 'models.py', path: 'modules/user/models.py', language: 'python' },
  { id: 'file:modules/user/repository.py', type: 'file', label: 'repository.py', path: 'modules/user/repository.py', language: 'python' },
  { id: 'file:modules/user/router.py', type: 'file', label: 'router.py', path: 'modules/user/router.py', language: 'python' },
  { id: 'file:modules/user/schemas.py', type: 'file', label: 'schemas.py', path: 'modules/user/schemas.py', language: 'python' },
  { id: 'file:modules/user/service.py', type: 'file', label: 'service.py', path: 'modules/user/service.py', language: 'python' },

  // modules/user_event_log
  { id: 'file:modules/user_event_log/__init__.py', type: 'file', label: '__init__.py', path: 'modules/user_event_log/__init__.py', language: 'python' },
  { id: 'file:modules/user_event_log/models.py', type: 'file', label: 'models.py', path: 'modules/user_event_log/models.py', language: 'python' },
  { id: 'file:modules/user_event_log/repository.py', type: 'file', label: 'repository.py', path: 'modules/user_event_log/repository.py', language: 'python' },
  { id: 'file:modules/user_event_log/router.py', type: 'file', label: 'router.py', path: 'modules/user_event_log/router.py', language: 'python' },
  { id: 'file:modules/user_event_log/service.py', type: 'file', label: 'service.py', path: 'modules/user_event_log/service.py', language: 'python' },

  // tests
  { id: 'file:tests/api_sweep_test.py', type: 'file', label: 'api_sweep_test.py', path: 'tests/api_sweep_test.py', language: 'python' },
  { id: 'file:tests/non_user_router_flow_test.py', type: 'file', label: 'non_user_router_flow_test.py', path: 'tests/non_user_router_flow_test.py', language: 'python' },
  { id: 'file:tests/user_router_flow_test.py', type: 'file', label: 'user_router_flow_test.py', path: 'tests/user_router_flow_test.py', language: 'python' },
];

// ─── Package Dependencies ───
const packageEdges: GraphEdge[] = [
  { id: 'package_dep:module:.->fastapi', source: 'module:.', target: 'package:fastapi', kind: 'package_dep' },
  { id: 'package_dep:module:.->sqlalchemy', source: 'module:.', target: 'package:sqlalchemy', kind: 'package_dep' },
  { id: 'package_dep:module:.->python-jose', source: 'module:.', target: 'package:python-jose', kind: 'package_dep' },
  { id: 'package_dep:module:.->google-auth', source: 'module:.', target: 'package:google-auth', kind: 'package_dep' },
  { id: 'package_dep:module:.->pymysql', source: 'module:.', target: 'package:pymysql', kind: 'package_dep' },
  { id: 'package_dep:module:.->alembic', source: 'module:.', target: 'package:alembic', kind: 'package_dep' },
  { id: 'package_dep:module:.->uvicorn', source: 'module:.', target: 'package:uvicorn', kind: 'package_dep' },
];

// ─── Contains (directory hierarchy) ───
const containsEdges: GraphEdge[] = [
  // module → module
  { id: 'contains:module:.->module:core', source: 'module:.', target: 'module:core', kind: 'contains' },
  { id: 'contains:module:.->module:modules', source: 'module:.', target: 'module:modules', kind: 'contains' },
  { id: 'contains:module:.->module:tests', source: 'module:.', target: 'module:tests', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/admin', source: 'module:modules', target: 'module:modules/admin', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/admin_auth', source: 'module:modules', target: 'module:modules/admin_auth', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/event', source: 'module:modules', target: 'module:modules/event', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/gacha', source: 'module:modules', target: 'module:modules/gacha', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/misc', source: 'module:modules', target: 'module:modules/misc', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/notice', source: 'module:modules', target: 'module:modules/notice', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/ranking', source: 'module:modules', target: 'module:modules/ranking', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/shop', source: 'module:modules', target: 'module:modules/shop', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/user', source: 'module:modules', target: 'module:modules/user', kind: 'contains' },
  { id: 'contains:module:modules->module:modules/user_event_log', source: 'module:modules', target: 'module:modules/user_event_log', kind: 'contains' },

  // module → file (used during expand)
  { id: 'contains:module:.->file:main.py', source: 'module:.', target: 'file:main.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/CONSTANTS.py', source: 'module:core', target: 'file:core/CONSTANTS.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/database.py', source: 'module:core', target: 'file:core/database.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/exceptions.py', source: 'module:core', target: 'file:core/exceptions.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/init_db.py', source: 'module:core', target: 'file:core/init_db.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/logging_config.py', source: 'module:core', target: 'file:core/logging_config.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/misc.py', source: 'module:core', target: 'file:core/misc.py', kind: 'contains' },
  { id: 'contains:module:core->file:core/security.py', source: 'module:core', target: 'file:core/security.py', kind: 'contains' },
  { id: 'contains:module:modules->file:modules/__init__.py', source: 'module:modules', target: 'file:modules/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/admin->file:modules/admin/__init__.py', source: 'module:modules/admin', target: 'file:modules/admin/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/admin->file:modules/admin/router.py', source: 'module:modules/admin', target: 'file:modules/admin/router.py', kind: 'contains' },
  { id: 'contains:module:modules/admin->file:modules/admin/service.py', source: 'module:modules/admin', target: 'file:modules/admin/service.py', kind: 'contains' },
  { id: 'contains:module:modules/admin->file:modules/admin/ui_router.py', source: 'module:modules/admin', target: 'file:modules/admin/ui_router.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/__init__.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/models.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/models.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/repository.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/router.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/router.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/schemas.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/service.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/service.py', kind: 'contains' },
  { id: 'contains:module:modules/admin_auth->file:modules/admin_auth/session_service.py', source: 'module:modules/admin_auth', target: 'file:modules/admin_auth/session_service.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/__init__.py', source: 'module:modules/event', target: 'file:modules/event/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/attendance_models.py', source: 'module:modules/event', target: 'file:modules/event/attendance_models.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/attendance_repository.py', source: 'module:modules/event', target: 'file:modules/event/attendance_repository.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/event_attendance_models.py', source: 'module:modules/event', target: 'file:modules/event/event_attendance_models.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/models.py', source: 'module:modules/event', target: 'file:modules/event/models.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/repository.py', source: 'module:modules/event', target: 'file:modules/event/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/event->file:modules/event/service.py', source: 'module:modules/event', target: 'file:modules/event/service.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/__init__.py', source: 'module:modules/gacha', target: 'file:modules/gacha/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/balpan_models.py', source: 'module:modules/gacha', target: 'file:modules/gacha/balpan_models.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/balpan_repository.py', source: 'module:modules/gacha', target: 'file:modules/gacha/balpan_repository.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/balpan_schemas.py', source: 'module:modules/gacha', target: 'file:modules/gacha/balpan_schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/models.py', source: 'module:modules/gacha', target: 'file:modules/gacha/models.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/repository.py', source: 'module:modules/gacha', target: 'file:modules/gacha/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/router.py', source: 'module:modules/gacha', target: 'file:modules/gacha/router.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/router_logs.py', source: 'module:modules/gacha', target: 'file:modules/gacha/router_logs.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/schemas.py', source: 'module:modules/gacha', target: 'file:modules/gacha/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/gacha->file:modules/gacha/service.py', source: 'module:modules/gacha', target: 'file:modules/gacha/service.py', kind: 'contains' },
  { id: 'contains:module:modules/misc->file:modules/misc/__init__.py', source: 'module:modules/misc', target: 'file:modules/misc/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/misc->file:modules/misc/router.py', source: 'module:modules/misc', target: 'file:modules/misc/router.py', kind: 'contains' },
  { id: 'contains:module:modules/misc->file:modules/misc/router_logs.py', source: 'module:modules/misc', target: 'file:modules/misc/router_logs.py', kind: 'contains' },
  { id: 'contains:module:modules/misc->file:modules/misc/schemas.py', source: 'module:modules/misc', target: 'file:modules/misc/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/notice->file:modules/notice/__init__.py', source: 'module:modules/notice', target: 'file:modules/notice/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/notice->file:modules/notice/models.py', source: 'module:modules/notice', target: 'file:modules/notice/models.py', kind: 'contains' },
  { id: 'contains:module:modules/notice->file:modules/notice/repository.py', source: 'module:modules/notice', target: 'file:modules/notice/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/notice->file:modules/notice/schemas.py', source: 'module:modules/notice', target: 'file:modules/notice/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/notice->file:modules/notice/service.py', source: 'module:modules/notice', target: 'file:modules/notice/service.py', kind: 'contains' },
  { id: 'contains:module:modules/ranking->file:modules/ranking/__init__.py', source: 'module:modules/ranking', target: 'file:modules/ranking/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/ranking->file:modules/ranking/schemas.py', source: 'module:modules/ranking', target: 'file:modules/ranking/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/ranking->file:modules/ranking/service.py', source: 'module:modules/ranking', target: 'file:modules/ranking/service.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/__init__.py', source: 'module:modules/shop', target: 'file:modules/shop/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/models.py', source: 'module:modules/shop', target: 'file:modules/shop/models.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/purchase_models.py', source: 'module:modules/shop', target: 'file:modules/shop/purchase_models.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/purchase_repository.py', source: 'module:modules/shop', target: 'file:modules/shop/purchase_repository.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/repository.py', source: 'module:modules/shop', target: 'file:modules/shop/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/router.py', source: 'module:modules/shop', target: 'file:modules/shop/router.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/router_logs.py', source: 'module:modules/shop', target: 'file:modules/shop/router_logs.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/schemas.py', source: 'module:modules/shop', target: 'file:modules/shop/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/shop->file:modules/shop/service.py', source: 'module:modules/shop', target: 'file:modules/shop/service.py', kind: 'contains' },
  { id: 'contains:module:modules/user->file:modules/user/__init__.py', source: 'module:modules/user', target: 'file:modules/user/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/user->file:modules/user/models.py', source: 'module:modules/user', target: 'file:modules/user/models.py', kind: 'contains' },
  { id: 'contains:module:modules/user->file:modules/user/repository.py', source: 'module:modules/user', target: 'file:modules/user/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/user->file:modules/user/router.py', source: 'module:modules/user', target: 'file:modules/user/router.py', kind: 'contains' },
  { id: 'contains:module:modules/user->file:modules/user/schemas.py', source: 'module:modules/user', target: 'file:modules/user/schemas.py', kind: 'contains' },
  { id: 'contains:module:modules/user->file:modules/user/service.py', source: 'module:modules/user', target: 'file:modules/user/service.py', kind: 'contains' },
  { id: 'contains:module:modules/user_event_log->file:modules/user_event_log/__init__.py', source: 'module:modules/user_event_log', target: 'file:modules/user_event_log/__init__.py', kind: 'contains' },
  { id: 'contains:module:modules/user_event_log->file:modules/user_event_log/models.py', source: 'module:modules/user_event_log', target: 'file:modules/user_event_log/models.py', kind: 'contains' },
  { id: 'contains:module:modules/user_event_log->file:modules/user_event_log/repository.py', source: 'module:modules/user_event_log', target: 'file:modules/user_event_log/repository.py', kind: 'contains' },
  { id: 'contains:module:modules/user_event_log->file:modules/user_event_log/router.py', source: 'module:modules/user_event_log', target: 'file:modules/user_event_log/router.py', kind: 'contains' },
  { id: 'contains:module:modules/user_event_log->file:modules/user_event_log/service.py', source: 'module:modules/user_event_log', target: 'file:modules/user_event_log/service.py', kind: 'contains' },
  { id: 'contains:module:tests->file:tests/api_sweep_test.py', source: 'module:tests', target: 'file:tests/api_sweep_test.py', kind: 'contains' },
  { id: 'contains:module:tests->file:tests/non_user_router_flow_test.py', source: 'module:tests', target: 'file:tests/non_user_router_flow_test.py', kind: 'contains' },
  { id: 'contains:module:tests->file:tests/user_router_flow_test.py', source: 'module:tests', target: 'file:tests/user_router_flow_test.py', kind: 'contains' },
];

// ─── Module Imports (derived from file imports) ───
const moduleEdges: GraphEdge[] = [
  { id: 'module_import:module:.->module:core', source: 'module:.', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:.->module:modules/admin', source: 'module:.', target: 'module:modules/admin', kind: 'module_import' },
  { id: 'module_import:module:.->module:modules/admin_auth', source: 'module:.', target: 'module:modules/admin_auth', kind: 'module_import' },
  { id: 'module_import:module:.->module:modules/gacha', source: 'module:.', target: 'module:modules/gacha', kind: 'module_import' },
  { id: 'module_import:module:.->module:modules/misc', source: 'module:.', target: 'module:modules/misc', kind: 'module_import' },
  { id: 'module_import:module:.->module:modules/shop', source: 'module:.', target: 'module:modules/shop', kind: 'module_import' },
  { id: 'module_import:module:.->module:modules/user', source: 'module:.', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:core', source: 'module:modules/admin', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/admin_auth', source: 'module:modules/admin', target: 'module:modules/admin_auth', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/event', source: 'module:modules/admin', target: 'module:modules/event', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/gacha', source: 'module:modules/admin', target: 'module:modules/gacha', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/misc', source: 'module:modules/admin', target: 'module:modules/misc', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/notice', source: 'module:modules/admin', target: 'module:modules/notice', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/shop', source: 'module:modules/admin', target: 'module:modules/shop', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/user', source: 'module:modules/admin', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/admin->module:modules/user_event_log', source: 'module:modules/admin', target: 'module:modules/user_event_log', kind: 'module_import' },
  { id: 'module_import:module:modules/admin_auth->module:core', source: 'module:modules/admin_auth', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/event->module:core', source: 'module:modules/event', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/event->module:modules/misc', source: 'module:modules/event', target: 'module:modules/misc', kind: 'module_import' },
  { id: 'module_import:module:modules/event->module:modules/user', source: 'module:modules/event', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/gacha->module:core', source: 'module:modules/gacha', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/gacha->module:modules/user', source: 'module:modules/gacha', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/gacha->module:modules/user_event_log', source: 'module:modules/gacha', target: 'module:modules/user_event_log', kind: 'module_import' },
  { id: 'module_import:module:modules/misc->module:core', source: 'module:modules/misc', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/misc->module:modules/notice', source: 'module:modules/misc', target: 'module:modules/notice', kind: 'module_import' },
  { id: 'module_import:module:modules/misc->module:modules/ranking', source: 'module:modules/misc', target: 'module:modules/ranking', kind: 'module_import' },
  { id: 'module_import:module:modules/misc->module:modules/user', source: 'module:modules/misc', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/misc->module:modules/user_event_log', source: 'module:modules/misc', target: 'module:modules/user_event_log', kind: 'module_import' },
  { id: 'module_import:module:modules/notice->module:core', source: 'module:modules/notice', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/ranking->module:modules/event', source: 'module:modules/ranking', target: 'module:modules/event', kind: 'module_import' },
  { id: 'module_import:module:modules/ranking->module:modules/user', source: 'module:modules/ranking', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/shop->module:core', source: 'module:modules/shop', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/shop->module:modules/gacha', source: 'module:modules/shop', target: 'module:modules/gacha', kind: 'module_import' },
  { id: 'module_import:module:modules/shop->module:modules/user', source: 'module:modules/shop', target: 'module:modules/user', kind: 'module_import' },
  { id: 'module_import:module:modules/shop->module:modules/user_event_log', source: 'module:modules/shop', target: 'module:modules/user_event_log', kind: 'module_import' },
  { id: 'module_import:module:modules/user->module:core', source: 'module:modules/user', target: 'module:core', kind: 'module_import' },
  { id: 'module_import:module:modules/user->module:modules/event', source: 'module:modules/user', target: 'module:modules/event', kind: 'module_import' },
  { id: 'module_import:module:modules/user->module:modules/gacha', source: 'module:modules/user', target: 'module:modules/gacha', kind: 'module_import' },
  { id: 'module_import:module:modules/user->module:modules/misc', source: 'module:modules/user', target: 'module:modules/misc', kind: 'module_import' },
  { id: 'module_import:module:modules/user->module:modules/shop', source: 'module:modules/user', target: 'module:modules/shop', kind: 'module_import' },
  { id: 'module_import:module:modules/user->module:modules/user_event_log', source: 'module:modules/user', target: 'module:modules/user_event_log', kind: 'module_import' },
  { id: 'module_import:module:modules/user_event_log->module:core', source: 'module:modules/user_event_log', target: 'module:core', kind: 'module_import' },
];

// ─── File Imports ───
const fileEdges: GraphEdge[] = [
  { id: 'file_import:file:core/init_db.py->file:core/database.py', source: 'file:core/init_db.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:core/security.py->file:core/CONSTANTS.py', source: 'file:core/security.py', target: 'file:core/CONSTANTS.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:core/CONSTANTS.py', source: 'file:main.py', target: 'file:core/CONSTANTS.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:core/init_db.py', source: 'file:main.py', target: 'file:core/init_db.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:core/logging_config.py', source: 'file:main.py', target: 'file:core/logging_config.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:core/misc.py', source: 'file:main.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/admin/router.py', source: 'file:main.py', target: 'file:modules/admin/router.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/admin/service.py', source: 'file:main.py', target: 'file:modules/admin/service.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/admin/ui_router.py', source: 'file:main.py', target: 'file:modules/admin/ui_router.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/admin_auth/router.py', source: 'file:main.py', target: 'file:modules/admin_auth/router.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/gacha/router.py', source: 'file:main.py', target: 'file:modules/gacha/router.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/misc/router.py', source: 'file:main.py', target: 'file:modules/misc/router.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/shop/router.py', source: 'file:main.py', target: 'file:modules/shop/router.py', kind: 'file_import' },
  { id: 'file_import:file:main.py->file:modules/user/router.py', source: 'file:main.py', target: 'file:modules/user/router.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:core/database.py', source: 'file:modules/admin/router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:core/misc.py', source: 'file:modules/admin/router.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/admin/service.py', source: 'file:modules/admin/router.py', target: 'file:modules/admin/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/admin_auth/service.py', source: 'file:modules/admin/router.py', target: 'file:modules/admin_auth/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/event/service.py', source: 'file:modules/admin/router.py', target: 'file:modules/event/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/misc/schemas.py', source: 'file:modules/admin/router.py', target: 'file:modules/misc/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/notice/schemas.py', source: 'file:modules/admin/router.py', target: 'file:modules/notice/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/notice/service.py', source: 'file:modules/admin/router.py', target: 'file:modules/notice/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/router.py->file:modules/user/service.py', source: 'file:modules/admin/router.py', target: 'file:modules/user/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/service.py->file:core/database.py', source: 'file:modules/admin/service.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/service.py->file:modules/event/attendance_repository.py', source: 'file:modules/admin/service.py', target: 'file:modules/event/attendance_repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/service.py->file:modules/gacha/models.py', source: 'file:modules/admin/service.py', target: 'file:modules/gacha/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/service.py->file:modules/gacha/repository.py', source: 'file:modules/admin/service.py', target: 'file:modules/gacha/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/service.py->file:modules/shop/repository.py', source: 'file:modules/admin/service.py', target: 'file:modules/shop/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/service.py->file:modules/user/repository.py', source: 'file:modules/admin/service.py', target: 'file:modules/user/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:core/database.py', source: 'file:modules/admin/ui_router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/admin/service.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/admin/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/admin_auth/repository.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/admin_auth/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/admin_auth/service.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/admin_auth/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/admin_auth/session_service.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/admin_auth/session_service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/event/models.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/event/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/event/service.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/event/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/gacha/balpan_models.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/gacha/balpan_models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/misc/schemas.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/misc/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/notice/schemas.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/notice/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/notice/service.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/notice/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/shop/purchase_models.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/shop/purchase_models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/user/models.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/user/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin/ui_router.py->file:modules/user_event_log/models.py', source: 'file:modules/admin/ui_router.py', target: 'file:modules/user_event_log/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/models.py->file:core/database.py', source: 'file:modules/admin_auth/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/repository.py->file:modules/admin_auth/models.py', source: 'file:modules/admin_auth/repository.py', target: 'file:modules/admin_auth/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/router.py->file:core/database.py', source: 'file:modules/admin_auth/router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/router.py->file:modules/admin_auth/repository.py', source: 'file:modules/admin_auth/router.py', target: 'file:modules/admin_auth/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/router.py->file:modules/admin_auth/schemas.py', source: 'file:modules/admin_auth/router.py', target: 'file:modules/admin_auth/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/router.py->file:modules/admin_auth/service.py', source: 'file:modules/admin_auth/router.py', target: 'file:modules/admin_auth/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/service.py->file:core/CONSTANTS.py', source: 'file:modules/admin_auth/service.py', target: 'file:core/CONSTANTS.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/service.py->file:core/database.py', source: 'file:modules/admin_auth/service.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/service.py->file:modules/admin_auth/repository.py', source: 'file:modules/admin_auth/service.py', target: 'file:modules/admin_auth/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/session_service.py->file:core/CONSTANTS.py', source: 'file:modules/admin_auth/session_service.py', target: 'file:core/CONSTANTS.py', kind: 'file_import' },
  { id: 'file_import:file:modules/admin_auth/session_service.py->file:modules/admin_auth/repository.py', source: 'file:modules/admin_auth/session_service.py', target: 'file:modules/admin_auth/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/attendance_models.py->file:core/database.py', source: 'file:modules/event/attendance_models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/attendance_repository.py->file:modules/event/attendance_models.py', source: 'file:modules/event/attendance_repository.py', target: 'file:modules/event/attendance_models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/attendance_repository.py->file:modules/event/event_attendance_models.py', source: 'file:modules/event/attendance_repository.py', target: 'file:modules/event/event_attendance_models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/event_attendance_models.py->file:core/database.py', source: 'file:modules/event/event_attendance_models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/models.py->file:core/database.py', source: 'file:modules/event/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/repository.py->file:modules/event/models.py', source: 'file:modules/event/repository.py', target: 'file:modules/event/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/repository.py->file:modules/user/models.py', source: 'file:modules/event/repository.py', target: 'file:modules/user/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/service.py->file:modules/event/repository.py', source: 'file:modules/event/service.py', target: 'file:modules/event/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/service.py->file:modules/misc/schemas.py', source: 'file:modules/event/service.py', target: 'file:modules/misc/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/event/service.py->file:modules/user/models.py', source: 'file:modules/event/service.py', target: 'file:modules/user/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/balpan_models.py->file:core/database.py', source: 'file:modules/gacha/balpan_models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/balpan_repository.py->file:modules/gacha/balpan_models.py', source: 'file:modules/gacha/balpan_repository.py', target: 'file:modules/gacha/balpan_models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/models.py->file:core/database.py', source: 'file:modules/gacha/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/repository.py->file:modules/gacha/models.py', source: 'file:modules/gacha/repository.py', target: 'file:modules/gacha/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:core/database.py', source: 'file:modules/gacha/router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:core/exceptions.py', source: 'file:modules/gacha/router.py', target: 'file:core/exceptions.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:core/misc.py', source: 'file:modules/gacha/router.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:core/security.py', source: 'file:modules/gacha/router.py', target: 'file:core/security.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:modules/gacha/balpan_schemas.py', source: 'file:modules/gacha/router.py', target: 'file:modules/gacha/balpan_schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:modules/gacha/router_logs.py', source: 'file:modules/gacha/router.py', target: 'file:modules/gacha/router_logs.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:modules/gacha/schemas.py', source: 'file:modules/gacha/router.py', target: 'file:modules/gacha/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router.py->file:modules/gacha/service.py', source: 'file:modules/gacha/router.py', target: 'file:modules/gacha/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/router_logs.py->file:modules/user_event_log/service.py', source: 'file:modules/gacha/router_logs.py', target: 'file:modules/user_event_log/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/service.py->file:core/exceptions.py', source: 'file:modules/gacha/service.py', target: 'file:core/exceptions.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/service.py->file:modules/gacha/balpan_repository.py', source: 'file:modules/gacha/service.py', target: 'file:modules/gacha/balpan_repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/service.py->file:modules/gacha/balpan_schemas.py', source: 'file:modules/gacha/service.py', target: 'file:modules/gacha/balpan_schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/service.py->file:modules/gacha/repository.py', source: 'file:modules/gacha/service.py', target: 'file:modules/gacha/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/service.py->file:modules/gacha/schemas.py', source: 'file:modules/gacha/service.py', target: 'file:modules/gacha/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/gacha/service.py->file:modules/user/repository.py', source: 'file:modules/gacha/service.py', target: 'file:modules/user/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:core/database.py', source: 'file:modules/misc/router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:core/misc.py', source: 'file:modules/misc/router.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:core/security.py', source: 'file:modules/misc/router.py', target: 'file:core/security.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/misc/router_logs.py', source: 'file:modules/misc/router.py', target: 'file:modules/misc/router_logs.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/misc/schemas.py', source: 'file:modules/misc/router.py', target: 'file:modules/misc/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/notice/schemas.py', source: 'file:modules/misc/router.py', target: 'file:modules/notice/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/notice/service.py', source: 'file:modules/misc/router.py', target: 'file:modules/notice/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/ranking/schemas.py', source: 'file:modules/misc/router.py', target: 'file:modules/ranking/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/ranking/service.py', source: 'file:modules/misc/router.py', target: 'file:modules/ranking/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router.py->file:modules/user/service.py', source: 'file:modules/misc/router.py', target: 'file:modules/user/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/misc/router_logs.py->file:modules/user_event_log/service.py', source: 'file:modules/misc/router_logs.py', target: 'file:modules/user_event_log/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/notice/models.py->file:core/database.py', source: 'file:modules/notice/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/notice/repository.py->file:modules/notice/models.py', source: 'file:modules/notice/repository.py', target: 'file:modules/notice/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/notice/service.py->file:modules/notice/repository.py', source: 'file:modules/notice/service.py', target: 'file:modules/notice/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/notice/service.py->file:modules/notice/schemas.py', source: 'file:modules/notice/service.py', target: 'file:modules/notice/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/ranking/service.py->file:modules/event/repository.py', source: 'file:modules/ranking/service.py', target: 'file:modules/event/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/ranking/service.py->file:modules/ranking/schemas.py', source: 'file:modules/ranking/service.py', target: 'file:modules/ranking/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/ranking/service.py->file:modules/user/repository.py', source: 'file:modules/ranking/service.py', target: 'file:modules/user/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/models.py->file:core/database.py', source: 'file:modules/shop/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/purchase_models.py->file:core/database.py', source: 'file:modules/shop/purchase_models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/purchase_repository.py->file:modules/shop/purchase_models.py', source: 'file:modules/shop/purchase_repository.py', target: 'file:modules/shop/purchase_models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/repository.py->file:modules/shop/models.py', source: 'file:modules/shop/repository.py', target: 'file:modules/shop/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:core/database.py', source: 'file:modules/shop/router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:core/exceptions.py', source: 'file:modules/shop/router.py', target: 'file:core/exceptions.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:core/misc.py', source: 'file:modules/shop/router.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:core/security.py', source: 'file:modules/shop/router.py', target: 'file:core/security.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:modules/shop/router_logs.py', source: 'file:modules/shop/router.py', target: 'file:modules/shop/router_logs.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:modules/shop/schemas.py', source: 'file:modules/shop/router.py', target: 'file:modules/shop/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router.py->file:modules/shop/service.py', source: 'file:modules/shop/router.py', target: 'file:modules/shop/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/router_logs.py->file:modules/user_event_log/service.py', source: 'file:modules/shop/router_logs.py', target: 'file:modules/user_event_log/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/service.py->file:core/exceptions.py', source: 'file:modules/shop/service.py', target: 'file:core/exceptions.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/service.py->file:modules/gacha/balpan_repository.py', source: 'file:modules/shop/service.py', target: 'file:modules/gacha/balpan_repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/service.py->file:modules/shop/purchase_repository.py', source: 'file:modules/shop/service.py', target: 'file:modules/shop/purchase_repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/service.py->file:modules/shop/repository.py', source: 'file:modules/shop/service.py', target: 'file:modules/shop/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/service.py->file:modules/shop/schemas.py', source: 'file:modules/shop/service.py', target: 'file:modules/shop/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/shop/service.py->file:modules/user/repository.py', source: 'file:modules/shop/service.py', target: 'file:modules/user/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/models.py->file:core/database.py', source: 'file:modules/user/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/repository.py->file:modules/shop/models.py', source: 'file:modules/user/repository.py', target: 'file:modules/shop/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/repository.py->file:modules/user/models.py', source: 'file:modules/user/repository.py', target: 'file:modules/user/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:core/CONSTANTS.py', source: 'file:modules/user/router.py', target: 'file:core/CONSTANTS.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:core/database.py', source: 'file:modules/user/router.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:core/exceptions.py', source: 'file:modules/user/router.py', target: 'file:core/exceptions.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:core/misc.py', source: 'file:modules/user/router.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:core/security.py', source: 'file:modules/user/router.py', target: 'file:core/security.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:modules/event/service.py', source: 'file:modules/user/router.py', target: 'file:modules/event/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:modules/misc/schemas.py', source: 'file:modules/user/router.py', target: 'file:modules/misc/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:modules/user/schemas.py', source: 'file:modules/user/router.py', target: 'file:modules/user/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:modules/user/service.py', source: 'file:modules/user/router.py', target: 'file:modules/user/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/router.py->file:modules/user_event_log/router.py', source: 'file:modules/user/router.py', target: 'file:modules/user_event_log/router.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/schemas.py->file:modules/gacha/balpan_schemas.py', source: 'file:modules/user/schemas.py', target: 'file:modules/gacha/balpan_schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/schemas.py->file:modules/shop/schemas.py', source: 'file:modules/user/schemas.py', target: 'file:modules/shop/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:core/CONSTANTS.py', source: 'file:modules/user/service.py', target: 'file:core/CONSTANTS.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:core/exceptions.py', source: 'file:modules/user/service.py', target: 'file:core/exceptions.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:core/misc.py', source: 'file:modules/user/service.py', target: 'file:core/misc.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/event/attendance_repository.py', source: 'file:modules/user/service.py', target: 'file:modules/event/attendance_repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/gacha/balpan_repository.py', source: 'file:modules/user/service.py', target: 'file:modules/gacha/balpan_repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/gacha/balpan_schemas.py', source: 'file:modules/user/service.py', target: 'file:modules/gacha/balpan_schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/misc/schemas.py', source: 'file:modules/user/service.py', target: 'file:modules/misc/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/shop/repository.py', source: 'file:modules/user/service.py', target: 'file:modules/shop/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/shop/service.py', source: 'file:modules/user/service.py', target: 'file:modules/shop/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/user/repository.py', source: 'file:modules/user/service.py', target: 'file:modules/user/repository.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user/service.py->file:modules/user/schemas.py', source: 'file:modules/user/service.py', target: 'file:modules/user/schemas.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user_event_log/models.py->file:core/database.py', source: 'file:modules/user_event_log/models.py', target: 'file:core/database.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user_event_log/repository.py->file:modules/user_event_log/models.py', source: 'file:modules/user_event_log/repository.py', target: 'file:modules/user_event_log/models.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user_event_log/router.py->file:modules/user_event_log/service.py', source: 'file:modules/user_event_log/router.py', target: 'file:modules/user_event_log/service.py', kind: 'file_import' },
  { id: 'file_import:file:modules/user_event_log/service.py->file:modules/user_event_log/repository.py', source: 'file:modules/user_event_log/service.py', target: 'file:modules/user_event_log/repository.py', kind: 'file_import' },
];

// ─── Side-Effect Imports (noqa: F401) ───
const sideEffectEdges: GraphEdge[] = [
  { id: 'side_effect:file:core/init_db.py->file:modules/admin_auth/models.py', source: 'file:core/init_db.py', target: 'file:modules/admin_auth/models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/event/attendance_models.py', source: 'file:core/init_db.py', target: 'file:modules/event/attendance_models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/event/event_attendance_models.py', source: 'file:core/init_db.py', target: 'file:modules/event/event_attendance_models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/event/models.py', source: 'file:core/init_db.py', target: 'file:modules/event/models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/gacha/balpan_models.py', source: 'file:core/init_db.py', target: 'file:modules/gacha/balpan_models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/gacha/models.py', source: 'file:core/init_db.py', target: 'file:modules/gacha/models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/notice/models.py', source: 'file:core/init_db.py', target: 'file:modules/notice/models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/shop/models.py', source: 'file:core/init_db.py', target: 'file:modules/shop/models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/shop/purchase_models.py', source: 'file:core/init_db.py', target: 'file:modules/shop/purchase_models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/user/models.py', source: 'file:core/init_db.py', target: 'file:modules/user/models.py', kind: 'side_effect_import' },
  { id: 'side_effect:file:core/init_db.py->file:modules/user_event_log/models.py', source: 'file:core/init_db.py', target: 'file:modules/user_event_log/models.py', kind: 'side_effect_import' },
];

// ─── Export ───
export const mockNodes: GraphNode[] = [...packages, ...modules, ...files];
export const mockEdges: GraphEdge[] = [...packageEdges, ...containsEdges, ...moduleEdges, ...fileEdges, ...sideEffectEdges];

export function getMockGraphByDepth(depth: GraphDepth) {
  const edgeFilter = (edges: GraphEdge[], nodeIds: Set<string>) =>
    edges.filter((e) => nodeIds.has(e.source) && nodeIds.has(e.target));

  let selectedNodes: GraphNode[];
  let selectedEdges: GraphEdge[];

  switch (depth) {
    case 'packages':
      selectedNodes = [...packages, modules[0]];
      selectedEdges = packageEdges;
      break;
    case 'modules':
    default:
      selectedNodes = [...packages, ...modules];
      selectedEdges = [...packageEdges, ...containsEdges.filter(e => e.target.startsWith('module:')), ...moduleEdges];
      break;
  }

  const ids = new Set(selectedNodes.map((n) => n.id));
  return { nodes: selectedNodes, edges: edgeFilter(selectedEdges, ids) };
}

export function getMockExpandModule(modulePath: string): { nodes: GraphNode[]; edges: GraphEdge[] } | null {
  const moduleId = `module:${modulePath}`;

  const childFileIds = new Set(
    containsEdges
      .filter((e) => e.source === moduleId && e.target.startsWith('file:'))
      .map((e) => e.target)
  );

  if (childFileIds.size === 0) return null;

  const moduleFiles = files.filter((f) => childFileIds.has(f.id));
  const relatedContains = containsEdges.filter(
    (e) => e.source === moduleId && childFileIds.has(e.target)
  );
  const relatedImports = [...fileEdges, ...sideEffectEdges].filter(
    (e) => childFileIds.has(e.source) || childFileIds.has(e.target)
  );

  return {
    nodes: moduleFiles,
    edges: [...relatedContains, ...relatedImports],
  };
}
